plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

jar {
    archiveFileName = 'jvm-mon-go.jar'
    manifest {
        attributes "Main-Class": "jvmmon.Agent"
        attributes "Agent-Class": "jvmmon.Agent"
        attributes "Premain-Class": "jvmmon.Agent"
        attributes "Can-Redefine-Classes": 'false'
        attributes "Can-Retransform-Classes": 'false'
        attributes 'Can-Set-Native-Method-Prefix': 'false'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
